AUGMENTATIONS_PER_IMAGE: 4
AUGMENTED_TRAIN_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN/data/augmented_train
BASE_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN
BATCH_SIZE: 64
DATA_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN/data
DROPOUT_RATE: 0.3
EPOCHS: 20
L1_FACTOR: 1e-6
L2_FACTOR: 1e-4
LEARNING_RATE: 0.001
MIN_DELTA: 1e-4
MODELS_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN/models
NUM_CLASSES: 10
PATIENCE: 5
SAMPLE_SIZE: 100
TEST_IMAGES_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN/data/test
TRAIN_IMAGES_DIR: /Users/aryansingh/Documents/CV_Practice/CV_CNN/data/train
TRAIN_LABELS_PATH: /Users/aryansingh/Documents/CV_Practice/CV_CNN/data/CIFAR-10_Train_Labels.csv
VALIDATION_SPLIT: 0.2
